MODE: 2
MODEL: 3
INPUT_SIZE: 0
TEST_FLIST: /content/drive/MyDrive/DATASET/test_flist.txt
TEST_MASK_FLIST: /content/drive/MyDrive/DATASET/test_mask_flist.txt
TEST_EDGE_FLIST: /content/drive/MyDrive/DATASET/test_flist.txt
RESULTS: /content/drive/MyDrive/DATASET/results2
LR: 0.0001
D2G_LR: 0.1
BETA1: 0.0
BETA2: 0.9
BATCH_SIZE: 8
SIGMA: 2
MAX_ITERS: 2000000
EDGE_THRESHOLD: 0.5
L1_LOSS_WEIGHT: 1
FM_LOSS_WEIGHT: 10
STYLE_LOSS_WEIGHT: 1
CONTENT_LOSS_WEIGHT: 1
INPAINT_ADV_LOSS_WEIGHT: 0.01
GAN_LOSS: nsgan
GAN_POOL_SIZE: 0
SAVE_INTERVAL: 1000
SAMPLE_INTERVAL: 1000
SAMPLE_SIZE: 12
EVAL_INTERVAL: 0
LOG_INTERVAL: 10
